language: php

php:
- '5.6'
- '7.0'

before_script:
  - composer self-update
  - composer install -n --no-scripts

script:
  - ./vendor/bin/phpcs --standard=psr2 -n --ignore=vendor .
  - ./vendor/bin/phpunit