sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build tests-with-report

script:
  - >
    docker-compose run
    --rm
    -e EX_SK_API_URL=$EX_SK_API_URL
    -e EX_SK_USERNAME=$EX_SK_USERNAME
    -e EX_SK_PASSWORD=$EX_SK_PASSWORD
    -e EX_SK_USER_ID=$EX_SK_USER_ID
    -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN
    tests-with-report
after_success:
  - docker images

deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true