version: '2'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - SKLIK_API_URL
      - SKLIK_API_TOKEN
      - SKLIK_API_USERNAME
      - SKLIK_API_PASSWORD
      - SKLIK_DATE_FROM
      - SKLIK_DATE_TO
